/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ronildo.facanha (https://sketchfab.com/ronildo.facanha)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/explore-the-magical-island-in-low-poly-3d-7487438f524e4e54959a6fea19751491
Title: Explore the Magical Island in Low Poly 3D
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

import islandScene from '../assets/3d/island.glb';
import {a} from '@react-spring/three'

const Island = (props) => {
  const islandRef = useRef()
  const { nodes, materials } = useGLTF(islandScene);
  console.log(nodes, materials);

  return (
    <a.group ref={islandRef} {...props}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Pano_Light}
      />
      <mesh   geometry={nodes.Object_5.geometry} material={materials.Pano} />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Fundo}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Madeira}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.Fundo}
      />
      <mesh
        
        
        geometry={nodes.Object_10.geometry}
        material={materials.Pano}
      />
      <mesh
        
        
        geometry={nodes.Object_11.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_13.geometry}
        material={materials.Madeira}
      />
      <mesh
        
        
        geometry={nodes.Object_14.geometry}
        material={materials.Fundo}
      />
      <mesh
        
        
        geometry={nodes.Object_15.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_16.geometry}
        material={materials.Vidro}
      />
      <mesh
        
        
        geometry={nodes.Object_18.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_19.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_21.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_22.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_24.geometry}
        material={materials.Concreto}
      />
      <mesh
        
        
        geometry={nodes.Object_25.geometry}
        material={materials.Pano}
      />
      <mesh
        
        
        geometry={nodes.Object_26.geometry}
        material={materials.Concreto_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_27.geometry}
        material={materials.Pano_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_28.geometry}
        material={materials.Madeira}
      />
      <mesh
        
        
        geometry={nodes.Object_29.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_30.geometry}
        material={materials.Vidro}
      />
      <mesh
        
        
        geometry={nodes.Object_31.geometry}
        material={materials.Fundo}
      />
      <mesh
        
        
        geometry={nodes.Object_33.geometry}
        material={materials.Concreto}
      />
      <mesh
        
        
        geometry={nodes.Object_34.geometry}
        material={materials.Madeira}
      />
      <mesh
        
        
        geometry={nodes.Object_35.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_36.geometry}
        material={materials.Fundo}
      />
      <mesh
        
        
        geometry={nodes.Object_38.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_39.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_41.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_42.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_44.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_45.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_47.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_48.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_50.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_51.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_53.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_54.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_56.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_57.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_59.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_60.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_62.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_64.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_66.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_68.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_69.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_71.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_73.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_75.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_77.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_79.geometry}
        material={materials.Concreto_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_81.geometry}
        material={materials.Madeira}
      />
      <mesh
        
        
        geometry={nodes.Object_82.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_84.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_85.geometry}
        material={materials.Madeira}
      />
      <mesh
        
        
        geometry={nodes.Object_87.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_88.geometry}
        material={materials.Madeira}
      />
      <mesh
        
        
        geometry={nodes.Object_90.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_91.geometry}
        material={materials.Madeira}
      />
      <mesh
        
        
        geometry={nodes.Object_93.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_94.geometry}
        material={materials.Madeira}
      />
      <mesh
        
        
        geometry={nodes.Object_96.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_98.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_100.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_102.geometry}
        material={materials.Concreto_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_104.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_106.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_108.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_110.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_112.geometry}
        material={materials.Madeira_Dark}
      />
      <mesh
        
        
        geometry={nodes.Object_113.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_115.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_117.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_119.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_121.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_123.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_125.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_127.geometry}
        material={materials.Grama_Light}
      />
      <mesh
        
        
        geometry={nodes.Object_129.geometry}
        material={materials.Madeira}
      />
      <mesh
        
        
        geometry={nodes.Object_131.geometry}
        material={materials.Terra}
      />
      <mesh
        
        
        geometry={nodes.Object_132.geometry}
        material={materials.Grama}
      />
      <mesh
        
        
        geometry={nodes.Object_133.geometry}
        material={materials.Areia}
      />
    </a.group>
  )
}

useGLTF.preload('/scene.gltf')

export default Island;
